baseURL = 'https://joshwright10.github.io'
languageCode = 'en-us'
title = 'DevOps Field Notes'
theme = 'beautifulhugo'
paginate = 5

[Author]
  name = "Josh Wright"
  github = "joshwright10"
  linkedin = "joshwright10"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[params]
    contentTypeName = "posts"
    showReadingTime = true
    pygmentsCodeFences = true
    pygmentsUseClasses = true