baseURL = 'https://joshwright10.github.io'
languageCode = 'en-us'
title = 'DevOps Field Notes'
theme = 'beautifulhugo'
paginate = 5

[Author]
  name = "Josh Wright"
  github = "joshwright10"
  linkedin = "joshwright10"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[params]
    mainSections = ["post","posts"]
    logo = "img/logo.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"
    comments= "page"
    contentTypeName = "posts"
    readingTime = true
    showRelatedPosts = true
    pygmentsCodeFences = true
    pygmentsUseClasses = true
    disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[params.giscus]
    repo = "joshwright10/joshwright10.github.io"
    repoID = "MDEwOlJlcG9zaXRvcnkxOTYwODUyODY="
    category = "Announcements"
    categoryID = "DIC_kwDOC7AGJs4CUzdm"
    mapping = "url"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "en"
    loading = "lazy"