baseURL = 'https://joshwright10.github.io'
languageCode = 'en-us'
title = 'DevOps Field Notes'
theme = 'beautifulhugo'
paginate = 5

[Author]
  name = "Josh Wright"
  github = "joshwright10"
  linkedin = "joshwright10"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[params]
    comments= "page"
    contentTypeName = "posts"
    showReadingTime = true
    pygmentsCodeFences = true
    pygmentsUseClasses = true

[params.giscus]
    repo = "joshwright10/joshwright10.github.io"
    repoID = "MDEwOlJlcG9zaXRvcnkxOTYwODUyODY="
    category = "Announcements"
    categoryID = "DIC_kwDOC7AGJs4CUzdm"
    mapping = "url"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "light"
    lang = "en"
    loading = "lazy"