baseURL = 'https://joshwright10.github.io/'
languageCode = 'en-us'
title = 'DevOps Field Notes'
theme = 'beautifulhugo'
paginate = 5
googleAnalytics = "G-L9PR34KNNJ"

[params]
    contentTypeName = "posts"
    showReadingTime = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true